version: "3.1"

services:
  # client:
  #   build: .
  #   volumes:
  #     - "./client:/app"
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - server

  server:
    build: .
    volumes:
      - "./server:/app"
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 666666
      MYSQL_DATABASE: ad_words
      MYSQL_USER: test
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
